### PR TITLE
Disable console.log & use the Protocol-relative URL

### PR DESCRIPTION
**Pull request by solarhell**

### CODE REVIEW

**Comment by alexazhou** [comment]
You had done a good job to use Protocol-relative .

Just a litter question, Seem like  you disabled the console.log()?
 I think add some code to control console.log in dashboard.js is better, too many script block in html may make people confused. And people who open the web console will want to see something,so we enable the console.log at default and give a option is better .

**Comment by alexazhou** [comment]
If you want add a option a disable console.log() , you can add some a var like dashboard.enable_log  to dashboard.js , and judge the var and control the console.log in dashboard.init() method .

Remember to keep the default option is enable console.log(), I think this is a better way, because people who open the web console will want to see some thing.

And don't need a add explain about this to readme.md , let's us keep readme simple and clear.

**Comment by alexazhou** [comment]
I have already fixed it and  merged,  be happy ~

**Comment by solarhell** [comment]
You are so cool, man! Thanks a lot.

**Pull request merged**
